### ISSUE TITLE
2.0 breaking changes

### ISSUE THREAD

**Issue by Tieske** [Kong/kong-pongo#322]
The intended breaking changes:

- [x] reduce compatibility to Kong versions 2.0+ #323  
- [x] change the base image to Ubuntu #323  
- [x] no longer start Cassandra dependency by default, only postgres (also changes the `init` command to change the defaults in `pongorc` file) #324 
- [x] rename `nightly` and `nightly-ee` to more appropriate names since they relate to the latest build of the `master` branch

Optional:
- [ ] remove "squid" dependency since it is a very specific dependency (from before the dynamic dependencies)

(this list is intended to be updated as we move along)

**Comment by Tieske** [comment]
2.0 is released, closing this. Upgrade instruction are in the Changelog section of the README.md file
